#!/usr/bin/env python3
"""Fail closed when a release artifact is unexpectedly large or opaque.

The repository intentionally contains a large development test suite and
several dependency lockfiles. They are useful in Git, but are not runtime
package data. This gate inspects the wheel and source distribution immediately
after PDM builds them, before either artifact can be uploaded or published.
"""

from __future__ import annotations

import argparse
import stat
import sys
import tarfile
import zipfile
from pathlib import Path, PurePosixPath


MIB = 1024 * 1024
MAX_ARTIFACT_BYTES = {"wheel": 7 * MIB, "sdist": 7 * MIB}
MAX_UNPACKED_BYTES = 32 * MIB
MAX_MEMBER_BYTES = 8 * MIB
MAX_FILE_MEMBERS = 2_000

FORBIDDEN_COMPONENTS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pycache__",
    "node_modules",
    "tests",
}
FORBIDDEN_BASENAMES = {
    ".coverage",
    ".ds_store",
    "npm-shrinkwrap.json",
    "package-lock.json",
    "pdm.lock",
    "pipfile.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "uv.lock",
    "yarn.lock",
}
FORBIDDEN_SUFFIXES = {".pyc", ".pyo"}

MAGIC_SIGNATURES = (
    (b"\x7fELF", "ELF executable/object"),
    (b"MZ", "PE executable"),
    (b"\xca\xfe\xba\xbe", "Java class/Mach-O binary"),
    (b"\xfe\xed\xfa\xce", "Mach-O binary"),
    (b"\xfe\xed\xfa\xcf", "Mach-O binary"),
    (b"\xce\xfa\xed\xfe", "Mach-O binary"),
    (b"\xcf\xfa\xed\xfe", "Mach-O binary"),
    (b"\x89PNG\r\n\x1a\n", "PNG image"),
    (b"\xff\xd8\xff", "JPEG image"),
    (b"GIF87a", "GIF image"),
    (b"GIF89a", "GIF image"),
    (b"%PDF-", "PDF document"),
    (b"PK\x03\x04", "ZIP/container"),
    (b"PK\x05\x06", "empty ZIP/container"),
    (b"\x1f\x8b", "gzip data"),
    (b"BZh", "bzip2 data"),
    (b"\xfd7zXZ\x00", "xz data"),
    (b"7z\xbc\xaf\x27\x1c", "7z archive"),
    (b"Rar!\x1a\x07", "RAR archive"),
    (b"SQLite format 3\x00", "SQLite database"),
    (b"\x00asm", "WebAssembly"),
    (b"OggS", "Ogg media"),
    (b"fLaC", "FLAC audio"),
)


def artifact_kind(path: Path) -> str | None:
    if path.name.endswith(".whl"):
        return "wheel"
    if path.name.endswith(".tar.gz"):
        return "sdist"
    return None


def _safe_parts(name: str) -> tuple[str, ...] | None:
    if (
        not name
        or "\\" in name
        or any(
            ord(character) < 32 or ord(character) == 127 for character in name
        )
    ):
        return None
    path = PurePosixPath(name)
    if (
        not path.parts
        or path.is_absolute()
        or any(part in {"", ".", ".."} or ":" in part for part in path.parts)
    ):
        return None
    return path.parts


def _logical_path(name: str, *, sdist_root: str | None) -> PurePosixPath | None:
    parts = _safe_parts(name)
    if parts is None:
        return None
    if sdist_root is not None:
        if not parts or parts[0] != sdist_root or len(parts) == 1:
            return None
        parts = parts[1:]
    return PurePosixPath(*parts)


def _path_policy_error(path: PurePosixPath) -> str | None:
    lowered = tuple(part.lower() for part in path.parts)
    forbidden = sorted(FORBIDDEN_COMPONENTS.intersection(lowered))
    if forbidden:
        return f"forbidden directory component(s): {', '.join(forbidden)}"
    if path.name.lower() in FORBIDDEN_BASENAMES:
        return f"forbidden lock/cache file: {path.name}"
    if path.suffix.lower() in FORBIDDEN_SUFFIXES:
        return f"forbidden generated bytecode: {path.suffix}"
    return None


def _package_path(path: PurePosixPath) -> PurePosixPath:
    if path.parts and path.parts[0] == "src":
        return PurePosixPath(*path.parts[1:])
    return path


def _expected_binary_error(
    path: PurePosixPath, data: bytes
) -> tuple[bool, str | None]:
    package_path = _package_path(path)
    rendered = package_path.as_posix()

    if rendered == "local_deep_research/web/static/favicon.png":
        valid = data.startswith(b"\x89PNG\r\n\x1a\n")
        return (
            True,
            None if valid else "approved PNG path has an invalid signature",
        )

    if rendered in {
        "local_deep_research/web/static/sounds/error.mp3",
        "local_deep_research/web/static/sounds/success.mp3",
    }:
        valid = data.startswith(b"ID3") or (
            len(data) >= 2 and data[0] == 0xFF and data[1] & 0xE0 == 0xE0
        )
        return (
            True,
            None if valid else "approved MP3 path has an invalid signature",
        )

    font_prefix = ("local_deep_research", "web", "static", "dist", "fonts")
    if package_path.parts[: len(font_prefix)] == font_prefix:
        suffix = package_path.suffix.lower()
        # Only font formats with a fixed, checkable magic are accepted here.
        # `.svg` fonts are plain text (no binary signature to verify) and
        # `.eot` starts with a size header instead of a fixed magic, so
        # neither can be added to this map without weakening the check
        # this gate exists to provide. If a frontend dependency bump ever
        # routes `.svg`/`.eot` output into dist/fonts/, the release build
        # will block here until this map is deliberately extended.
        signatures = {
            ".ttf": (b"\x00\x01\x00\x00", b"OTTO"),
            ".woff": (b"wOFF",),
            ".woff2": (b"wOF2",),
        }
        expected = signatures.get(suffix)
        if expected is None:
            return (
                True,
                f"unsupported generated font type: {suffix or '<none>'}",
            )
        valid = any(data.startswith(signature) for signature in expected)
        return True, None if valid else f"invalid {suffix} font signature"

    return False, None


def _unexpected_binary_reason(data: bytes) -> str | None:
    for signature, description in MAGIC_SIGNATURES:
        if data.startswith(signature):
            return description
    if data.startswith(b"RIFF") and data[8:12] in {b"AVI ", b"WAVE", b"WEBP"}:
        return "RIFF binary"
    if len(data) >= 12 and data[4:8] == b"ftyp":
        return "ISO media container"
    if b"\x00" in data:
        return "NUL byte"
    try:
        data.decode("utf-8")
    except UnicodeDecodeError:
        return "non-UTF-8 content"
    controls = sum(
        1
        for byte in data
        if (byte < 32 and byte not in {9, 10, 12, 13}) or byte == 127
    )
    if controls >= 8 and controls / max(len(data), 1) >= 0.01:
        return "dense binary control bytes"
    return None


def _content_policy_error(path: PurePosixPath, data: bytes) -> str | None:
    expected_binary, error = _expected_binary_error(path, data)
    if expected_binary:
        return error
    reason = _unexpected_binary_reason(data)
    if reason is not None:
        return f"unexpected binary content ({reason})"
    return None


def _resource_errors(file_count: int, unpacked_bytes: int) -> list[str]:
    errors = []
    if file_count > MAX_FILE_MEMBERS:
        errors.append(
            f"contains {file_count:,} files; limit is {MAX_FILE_MEMBERS:,}"
        )
    if unpacked_bytes > MAX_UNPACKED_BYTES:
        errors.append(
            f"unpacks to {unpacked_bytes:,} bytes; limit is "
            f"{MAX_UNPACKED_BYTES:,}"
        )
    return errors


def _inspect_wheel(path: Path) -> tuple[int, int, list[str]]:
    errors: list[str] = []
    with zipfile.ZipFile(path) as archive:
        members = archive.infolist()
        files = [member for member in members if not member.is_dir()]
        unpacked = sum(member.file_size for member in files)
        errors.extend(_resource_errors(len(files), unpacked))
        if errors:
            return len(files), unpacked, errors

        seen: set[PurePosixPath] = set()
        for member in members:
            logical = _logical_path(member.filename, sdist_root=None)
            if logical is None:
                errors.append(f"unsafe wheel member path: {member.filename!r}")
                continue
            mode = member.external_attr >> 16
            if mode and stat.S_ISLNK(mode):
                errors.append(f"symbolic link is not permitted: {logical}")
                continue
            if member.is_dir():
                error = _path_policy_error(logical)
                if error is None and member.file_size:
                    error = "directory entry carries data"
                if error is not None:
                    errors.append(f"{logical}: {error}")
                continue
            if logical in seen:
                errors.append(f"duplicate wheel member: {logical}")
                continue
            seen.add(logical)
            if member.flag_bits & 0x1:
                errors.append(
                    f"encrypted wheel member is not permitted: {logical}"
                )
                continue
            if member.file_size > MAX_MEMBER_BYTES:
                errors.append(
                    f"{logical}: {member.file_size:,} bytes exceeds the per-file "
                    f"limit of {MAX_MEMBER_BYTES:,}"
                )
                continue

            error = _path_policy_error(logical)
            if error is not None:
                errors.append(f"{logical}: {error}")
                continue
            try:
                data = archive.read(member)
            except (OSError, RuntimeError) as exc:
                errors.append(f"{logical}: unable to read member: {exc}")
                continue
            error = _content_policy_error(logical, data)
            if error is not None:
                errors.append(f"{logical}: {error}")

    return len(files), unpacked, errors


def _inspect_sdist(path: Path) -> tuple[int, int, list[str]]:
    errors: list[str] = []
    with tarfile.open(path, mode="r:gz") as archive:
        members = archive.getmembers()
        roots = {
            parts[0]
            for member in members
            if (parts := _safe_parts(member.name)) is not None
        }
        if len(roots) != 1:
            errors.append(
                "source distribution must have exactly one safe root directory; "
                f"found {sorted(roots)!r}"
            )
            return 0, 0, errors
        root = next(iter(roots))

        files = [member for member in members if member.isfile()]
        unpacked = sum(member.size for member in files)
        errors.extend(_resource_errors(len(files), unpacked))
        if errors:
            return len(files), unpacked, errors

        seen: set[PurePosixPath] = set()
        for member in members:
            # The archive's own root is a valid directory entry. Every other
            # directory still needs path validation before it can be ignored.
            if member.isdir() and _safe_parts(member.name) == (root,):
                continue
            logical = _logical_path(member.name, sdist_root=root)
            if logical is None:
                errors.append(f"unsafe sdist member path: {member.name!r}")
                continue
            if member.isdir():
                error = _path_policy_error(logical)
                if error is None and member.size:
                    error = "directory entry carries data"
                if error is not None:
                    errors.append(f"{logical}: {error}")
                continue
            if not member.isfile():
                errors.append(
                    f"non-regular archive member is not permitted: {logical}"
                )
                continue
            if logical in seen:
                errors.append(f"duplicate sdist member: {logical}")
                continue
            seen.add(logical)
            if member.size > MAX_MEMBER_BYTES:
                errors.append(
                    f"{logical}: {member.size:,} bytes exceeds the per-file limit "
                    f"of {MAX_MEMBER_BYTES:,}"
                )
                continue

            error = _path_policy_error(logical)
            if error is not None:
                errors.append(f"{logical}: {error}")
                continue
            extracted = archive.extractfile(member)
            if extracted is None:
                errors.append(f"{logical}: unable to read regular member")
                continue
            data = extracted.read()
            error = _content_policy_error(logical, data)
            if error is not None:
                errors.append(f"{logical}: {error}")

    return len(files), unpacked, errors


def _largest_members(path: Path, kind: str) -> list[tuple[str, int]]:
    """Return up to 5 largest regular-file members, largest first.

    Best-effort diagnostics only: an artifact this is called for has
    already failed the overall size limit, so if it also can't be parsed
    (e.g. it's corrupt), this returns an empty list rather than raising.
    """
    try:
        if kind == "wheel":
            with zipfile.ZipFile(path) as archive:
                sized = [
                    (member.filename, member.file_size)
                    for member in archive.infolist()
                    if not member.is_dir()
                ]
        else:
            with tarfile.open(path, mode="r:gz") as archive:
                sized = [
                    (member.name, member.size)
                    for member in archive.getmembers()
                    if member.isfile()
                ]
    except (OSError, tarfile.TarError, zipfile.BadZipFile):
        return []
    sized.sort(key=lambda item: item[1], reverse=True)
    return sized[:5]


def inspect_artifact(path: Path) -> tuple[dict[str, int | str], list[str]]:
    kind = artifact_kind(path)
    summary: dict[str, int | str] = {
        "kind": kind or "unknown",
        "size": 0,
        "files": 0,
        "unpacked": 0,
    }
    if kind is None:
        return summary, [f"unsupported artifact type: {path}"]
    try:
        size = path.stat().st_size
    except OSError as exc:
        return summary, [f"unable to stat {path}: {exc}"]
    summary["size"] = size
    if size > MAX_ARTIFACT_BYTES[kind]:
        error = (
            f"{kind} is {size:,} bytes; limit is {MAX_ARTIFACT_BYTES[kind]:,}"
        )
        largest = _largest_members(path, kind)
        if largest:
            details = ", ".join(
                f"{name} ({member_size:,} bytes)"
                for name, member_size in largest
            )
            error = f"{error}; largest members: {details}"
        return summary, [error]

    try:
        if kind == "wheel":
            files, unpacked, errors = _inspect_wheel(path)
        else:
            files, unpacked, errors = _inspect_sdist(path)
    except (OSError, tarfile.TarError, zipfile.BadZipFile) as exc:
        return summary, [f"cannot inspect {kind}: {exc}"]
    summary["files"] = files
    summary["unpacked"] = unpacked
    return summary, errors


def _discover(inputs: list[Path]) -> tuple[list[Path], list[str]]:
    if len(inputs) != 1 or not inputs[0].is_dir():
        return inputs, []

    directory = inputs[0]
    children = sorted(directory.iterdir())
    artifacts = [
        path
        for path in children
        if path.is_file() and artifact_kind(path) is not None
    ]
    unexpected = [
        path.name
        for path in children
        if not (path.is_file() and artifact_kind(path) is not None)
    ]
    errors = []
    if unexpected:
        errors.append(f"unexpected files in {directory}: {unexpected!r}")
    for kind in ("wheel", "sdist"):
        matches = [path for path in artifacts if artifact_kind(path) == kind]
        if len(matches) != 1:
            errors.append(
                f"expected exactly one {kind} in {directory}; found {len(matches)}"
            )
    return artifacts, errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "artifacts",
        nargs="+",
        type=Path,
        help="artifact files, or one directory containing one wheel and one sdist",
    )
    args = parser.parse_args(argv)

    artifacts, errors = _discover(args.artifacts)
    summaries = []
    for artifact in artifacts:
        summary, artifact_errors = inspect_artifact(artifact)
        summaries.append((artifact, summary))
        errors.extend(f"{artifact}: {error}" for error in artifact_errors)

    if errors:
        print("Package artifact policy failed:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    for artifact, summary in summaries:
        print(
            f"OK {artifact}: {summary['kind']}, {summary['size']:,} bytes, "
            f"{summary['files']:,} files, {summary['unpacked']:,} unpacked bytes"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
